export {
  ComboboxRoot,
  ComboboxInput,
  ComboboxTrigger,
  ComboboxClear,
  ComboboxAnchor,
  ComboboxPositioner,
  ComboboxPopup,
  ComboboxEmpty,
  ComboboxOption,
  ComboboxOptionGroup,
  ComboboxOptionGroupLabel,
  ComboboxArrow,
  ComboboxStatus,
  ComboboxValue,
  type ComboboxRootProps,
  type ComboboxInputProps,
  type ComboboxTriggerProps,
  type ComboboxClearProps,
  type ComboboxAnchorProps,
  type ComboboxPositionerProps,
  type ComboboxPopupProps,
  type ComboboxEmptyProps,
  type ComboboxOptionProps,
  type ComboboxOptionGroupProps,
  type ComboboxOptionGroupLabelProps,
  type ComboboxArrowProps,
  type ComboboxStatusProps,
  type ComboboxValueProps,
  type ComboboxValueState,
} from './combobox.js';

import {
  ComboboxRoot,
  ComboboxInput,
  ComboboxTrigger,
  ComboboxClear,
  ComboboxAnchor,
  ComboboxPositioner,
  ComboboxPopup,
  ComboboxEmpty,
  ComboboxOption,
  ComboboxOptionGroup,
  ComboboxOptionGroupLabel,
  ComboboxArrow,
  ComboboxStatus,
  ComboboxValue,
} from './combobox.js';

export const Combobox = {
  Root: ComboboxRoot,
  Input: ComboboxInput,
  Trigger: ComboboxTrigger,
  Clear: ComboboxClear,
  Anchor: ComboboxAnchor,
  Positioner: ComboboxPositioner,
  Popup: ComboboxPopup,
  Empty: ComboboxEmpty,
  Option: ComboboxOption,
  OptionGroup: ComboboxOptionGroup,
  OptionGroupLabel: ComboboxOptionGroupLabel,
  Arrow: ComboboxArrow,
  Status: ComboboxStatus,
  Value: ComboboxValue,
};

export { type AutocompleteMode } from './context.js';
