// Public barrel for @hono-preact/ui. Primitives and components are exported
// here as they land in subsequent tasks.
export { mergeRefs } from './merge-refs.js';
export { useRender, type RenderProp } from './use-render.js';
export { useControllableState } from './use-controllable-state.js';
export {
  usePosition,
  placementFor,
  sideAlignFromPlacement,
  type UsePositionOptions,
  type PositionState,
  type Side,
  type Align,
} from './use-position.js';
export { useDismiss, type UseDismissOptions } from './use-dismiss.js';
export { type DismissReason } from './dismiss-stack.js';
export {
  useFocusReturn,
  type UseFocusReturnOptions,
} from './use-focus-return.js';
export {
  usePresence,
  type UsePresenceOptions,
  type UsePresenceResult,
  type PresenceStatus,
} from './use-presence.js';
export { useSafeArea, type UseSafeAreaOptions } from './use-safe-area.js';
export {
  Dialog,
  DialogRoot,
  DialogTrigger,
  DialogPopup,
  DialogTitle,
  DialogDescription,
  DialogClose,
  type DialogRootProps,
  type DialogTriggerProps,
  type DialogPopupProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
  type DialogCloseProps,
} from './dialog/index.js';
export {
  Popover,
  PopoverRoot,
  PopoverTrigger,
  PopoverAnchor,
  PopoverPositioner,
  PopoverPopup,
  PopoverArrow,
  PopoverTitle,
  PopoverDescription,
  PopoverClose,
  type PopoverRootProps,
  type PopoverTriggerProps,
  type PopoverAnchorProps,
  type PopoverPositionerProps,
  type PopoverPopupProps,
  type PopoverArrowProps,
  type PopoverTitleProps,
  type PopoverDescriptionProps,
  type PopoverCloseProps,
} from './popover/index.js';
export {
  Tooltip,
  TooltipRoot,
  TooltipTrigger,
  TooltipPositioner,
  TooltipPopup,
  TooltipArrow,
  type TooltipRootProps,
  type TooltipTriggerProps,
  type TooltipPositionerProps,
  type TooltipPopupProps,
  type TooltipArrowProps,
} from './tooltip/index.js';
export {
  Menu,
  MenuRoot,
  MenuTrigger,
  MenuPositioner,
  MenuPopup,
  MenuItem,
  MenuCheckboxItem,
  MenuRadioGroup,
  MenuRadioItem,
  MenuSeparator,
  MenuGroup,
  MenuGroupLabel,
  MenuArrow,
  SubmenuRoot,
  SubmenuTrigger,
  SubmenuPositioner,
  SubmenuPopup,
  type MenuRootProps,
  type MenuTriggerProps,
  type MenuPositionerProps,
  type MenuPopupProps,
  type MenuItemProps,
  type MenuCheckboxItemProps,
  type MenuRadioGroupProps,
  type MenuRadioItemProps,
  type MenuSeparatorProps,
  type MenuGroupProps,
  type MenuGroupLabelProps,
  type MenuArrowProps,
  type SubmenuRootProps,
  type SubmenuTriggerProps,
  type SubmenuPositionerProps,
  type SubmenuPopupProps,
} from './menu/index.js';
export {
  ContextMenu,
  ContextMenuRoot,
  ContextMenuTrigger,
  type ContextMenuRootProps,
  type ContextMenuTriggerProps,
} from './context-menu/index.js';
export {
  useListNavigation,
  getItems,
  wrapNext,
  wrapPrev,
  matchTypeahead,
  type UseListNavigationOptions,
  type ListNavigation,
  type ListNavigationMode,
} from './list-navigation.js';
export { useTypeahead, type UseTypeaheadOptions } from './use-typeahead.js';
export {
  Select,
  SelectRoot,
  SelectTrigger,
  SelectValue,
  SelectPositioner,
  SelectPopup,
  SelectOption,
  SelectOptionGroup,
  SelectOptionGroupLabel,
  SelectArrow,
  OPTION_SELECTOR,
  type SelectRootProps,
  type SelectTriggerProps,
  type SelectValueProps,
  type SelectPositionerProps,
  type SelectPopupProps,
  type SelectOptionProps,
  type SelectOptionGroupProps,
  type SelectOptionGroupLabelProps,
  type SelectArrowProps,
} from './select/index.js';
export {
  Combobox,
  ComboboxRoot,
  ComboboxInput,
  ComboboxTrigger,
  ComboboxClear,
  ComboboxAnchor,
  ComboboxPositioner,
  ComboboxPopup,
  ComboboxEmpty,
  ComboboxOption,
  ComboboxOptionGroup,
  ComboboxOptionGroupLabel,
  ComboboxArrow,
  ComboboxStatus,
  ComboboxValue,
  type ComboboxRootProps,
  type ComboboxInputProps,
  type ComboboxTriggerProps,
  type ComboboxClearProps,
  type ComboboxAnchorProps,
  type ComboboxPositionerProps,
  type ComboboxPopupProps,
  type ComboboxEmptyProps,
  type ComboboxOptionProps,
  type ComboboxOptionGroupProps,
  type ComboboxOptionGroupLabelProps,
  type ComboboxArrowProps,
  type ComboboxStatusProps,
  type ComboboxValueProps,
  type ComboboxValueState,
  type AutocompleteMode,
} from './combobox/index.js';
export { matchSubstring } from './combobox/autocomplete.js';
